# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fc4949cf8e3dfc1dc455b84f4b392c4b58fd9865b61ba43bba5da8c6e6b12a285e3c1335dcf83d66c9210468da8add38ef75f2ba9e38503d0036d0d56dc0272

test:
  secret_key_base: 5c8743d9e2429dec021fbaa86a78ca2bff294d63b93f27b610a4250324e48e82de14d25cd038e7255b29d0f6939c4c3d00ab5cb3a55834132f5e81ec7ec1d801

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
